import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Quicksand, Ubuntu } from 'next/font/google'
import './globals.css'



// import Font Awesome CSS
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

//const inter = Inter({ subsets: ['latin'] })

const bodyFont = Quicksand({
  weight: ['300', '700'],
  variable: '--body-font',
  subsets: ['latin'],
  display: 'swap',
});

const titleFont = Ubuntu({
  weight: '700',
  variable: '--title-font',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${titleFont.variable} ${bodyFont.variable}`} >
      <body >{children}</body>
    </ html>
  )
}
